In [3]:
import numpy as np
import pandas as pd
import re

from utils.text_cleaning import stopword_remove, year_conversion

In [13]:
data = pd.read_csv('../artifacts/raw/anime-dataset-2023.csv')

In [14]:
data.head(3)

,anime_id,Name,English name,Other name,Score,Genres,Synopsis,Type,Episodes,Aired,...,Studios,Source,Duration,Rating,Rank,Popularity,Favorites,Scored By,Members,Image URL
0,1,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,8.75,"Action, Award Winning, Sci-Fi","Crime is timeless. By the year 2071, humanity ...",TV,26.0,"Apr 3, 1998 to Apr 24, 1999",...,Sunrise,Original,24 min per ep,R - 17+ (violence & profanity),41.0,43,78525,914193.0,1771505,https://cdn.myanimelist.net/images/anime/4/196...
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,カウボーイビバップ 天国の扉,8.38,"Action, Sci-Fi","Another day, another bounty—such is the life o...",Movie,1.0,"Sep 1, 2001",...,Bones,Original,1 hr 55 min,R - 17+ (violence & profanity),189.0,602,1448,206248.0,360978,https://cdn.myanimelist.net/images/anime/1439/...
2,6,Trigun,Trigun,トライガン,8.22,"Action, Adventure, Sci-Fi","Vash the Stampede is the man with a $$60,000,0...",TV,26.0,"Apr 1, 1998 to Sep 30, 1998",...,Madhouse,Manga,24 min per ep,PG-13 - Teens 13 or older,328.0,246,15035,356739.0,727252,https://cdn.myanimelist.net/images/anime/7/203...

In [15]:
data.shape

(24905, 24)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24905 entries, 0 to 24904
Data columns (total 24 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   anime_id      24905 non-null  int64
 1   Name          24905 non-null  object
 2   English name  24905 non-null  object
 3   Other name    24905 non-null  object
 4   Score         24905 non-null  object
 5   Genres        24905 non-null  object
 6   Synopsis      24905 non-null  object
 7   Type          24905 non-null  object
 8   Episodes      24905 non-null  object
 9   Aired         24905 non-null  object
 10  Premiered     24905 non-null  object
 11  Status        24905 non-null  object
 12  Producers     24905 non-null  object
 13  Licensors     24905 non-null  object
 14  Studios       24905 non-null  object
 15  Source        24905 non-null  object
 16  Duration      24905 non-null  object
 17  Rating        24905 non-null  object
 18  Rank          24905 non-null  object
 19  Popularity    24905 non-null  int64
 20  Favorites     24905 non-null  int64
 21  Scored By     24905 non-null  object
 22  Members       24905 non-null  int64
 23  Image URL     24905 non-null  object
dtypes: int64(4), object(20)
memory usage: 4.6+ MB

In [17]:
data['Aired']

0         Apr 3, 1998 to Apr 24, 1999
1                         Sep 1, 2001
2         Apr 1, 1998 to Sep 30, 1998
3         Jul 3, 2002 to Dec 25, 2002
4        Sep 30, 2004 to Sep 29, 2005
                     ...
24900                Jul 4, 2023 to ?
24901               Jul 27, 2023 to ?
24902               Jul 19, 2023 to ?
24903                    Apr 23, 2022
24904                     Sep 5, 2022
Name: Aired, Length: 24905, dtype: object

In [18]:
data.columns

Index(['anime_id', 'Name', 'English name', 'Other name', 'Score', 'Genres',
       'Synopsis', 'Type', 'Episodes', 'Aired', 'Premiered', 'Status',
       'Producers', 'Licensors', 'Studios', 'Source', 'Duration', 'Rating',
       'Rank', 'Popularity', 'Favorites', 'Scored By', 'Members', 'Image URL'],
      dtype='object')

In [19]:
data['year'] = data['Aired'].apply(year_conversion)
data['year']

0        1998
1        2001
2        1998
3        2002
4        2004
         ...
24900    2023
24901    2023
24902    2023
24903    2022
24904    2022
Name: year, Length: 24905, dtype: object

In [21]:
data['year'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 24905 entries, 0 to 24904
Series name: year
Non-Null Count  Dtype
--------------  -----
23990 non-null  object
dtypes: object(1)
memory usage: 194.7+ KB

In [22]:
df = data[['Name', 'English name', 'Score', 'Genres', 'Synopsis', 'Type', 'Episodes', 'Rating', 'Members', 'year']]

In [24]:
df.head()

,Name,English name,Score,Genres,Synopsis,Type,Episodes,Rating,Members,year
0,Cowboy Bebop,Cowboy Bebop,8.75,"Action, Award Winning, Sci-Fi","Crime is timeless. By the year 2071, humanity ...",TV,26.0,R - 17+ (violence & profanity),1771505,1998
1,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,8.38,"Action, Sci-Fi","Another day, another bounty—such is the life o...",Movie,1.0,R - 17+ (violence & profanity),360978,2001
2,Trigun,Trigun,8.22,"Action, Adventure, Sci-Fi","Vash the Stampede is the man with a $$60,000,0...",TV,26.0,PG-13 - Teens 13 or older,727252,1998
3,Witch Hunter Robin,Witch Hunter Robin,7.25,"Action, Drama, Mystery, Supernatural",Robin Sena is a powerful craft user drafted in...,TV,26.0,PG-13 - Teens 13 or older,111931,2002
4,Bouken Ou Beet,Beet the Vandel Buster,6.94,"Adventure, Fantasy, Supernatural",It is the dark century and the people are suff...,TV,52.0,PG - Children,15001,2004

In [4]:
from similarity.cosine_similarity import SimilarityCalculator

In [5]:
calculator = SimilarityCalculator('tdf-idf')
calculator.load_model()

In [6]:
result = calculator.compute()

SimilarityCalculationException: Failed to compute cosine similarity (Error Code: The 'X' parameter of cosine_similarity must be an array-like or a sparse matrix. Got None instead.)

In [7]:
from scipy.sparse import load_npz
from pathlib import Path
from config.path import FEATURE_DIR

matrix_path = FEATURE_DIR / 'tfidf_matrix.npz'
feature_matrix = load_npz(matrix_path)

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(feature_matrix, feature_matrix)

array([[1.        , 0.29343572, 0.02121748, ..., 0.02052628, 0.        ,
        0.        ],
       [0.29343572, 1.        , 0.03319742, ..., 0.0347859 , 0.        ,
        0.        ],
       [0.02121748, 0.03319742, 1.        , ..., 0.03491578, 0.        ,
        0.        ],
       ...,
       [0.02052628, 0.0347859 , 0.03491578, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.36480356],
       [0.        , 0.        , 0.        , ..., 0.        , 0.36480356,
        1.        ]], shape=(24905, 24905))